workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.rat.mobile"
        JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    scripts:
      - name: Build Android APK with Java 8
        script: |
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          java -version
          cd app
          ../gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk