workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.rat.mobile"
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2048m --add-modules java.xml.bind --add-exports java.xml.bind/javax.xml.bind=ALL-UNNAMED"
    scripts:
      - name: Build APK
        script: |
          cd app
          ../gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk